### ISSUE TITLE
Research app creation DSL

### ISSUE THREAD

**Issue by nzoschke** [nzoschke/ferret#3]
The suite of ferret tests implicitly defines a set of test apps. The "get or create" bash pattern works, but is ugly and doesn't offer any management of test app state.

Research a DSL that explicitly defines the set of test apps, code, and config, and ideally can converge between the definition and the running formation over time.

**Comment by ericfode** [comment]
It seems that ferrets accomplish the goal:
Consistently exercise parts of a system.

First some vocab:
Ferret - a script that exercises a part of the system. (all the stuff in the test folder)
FerretPin - The environment needed for a ferret to operate, this is usually one or more heroku apps (currently in apps folder and hacked into the setup part of each ferret script).
FerretCage - The server managing all of this. (currently ferret.rb) 

The process of exercising features can be divided in to the following steps:
1. Preparation:
    a. An environment that the feature can be isolated in on the system being exercised. (spinning up a heroku app)
    b. A ferret to exercise the feature using said app.  ( Could be anything from a bash script to some ruby )
2. Interval execution: 
    a. Execute ferret.
    b. Reset/modify environment if needed.
3. Aggregate collected data:
    a. ferret output.
    b. server output?

2 and 3 are async.
The following questions have to be answered:
Ferret: 
1. What does it do when testing
2. How often does it run
3. cleanup/setup/init/destroy

FerretPen:
1. What does it do
2. Any periodic operations (like recurl restarts)
3. init/destroy/update

FerretCage:
1. What ferrets go with what pins
2. How often do they all run
3. How many ferrets to run at once

More to come...
